import { ChatService } from './../../services/chat-service';
import { Component, inject, signal, WritableSignal } from '@angular/core';
import { VenueService } from '../../services/venue-service';
import { Venue, VenueUi } from '../../models/Venue';
import { CardModule } from 'primeng/card';
import { ButtonModule } from 'primeng/button';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { GenerateService } from '../../services/generate-service';

@Component({
  selector: 'app-venues-component',
  imports: [CardModule, ButtonModule, CommonModule],
  templateUrl: './venues-component.html',
  styleUrl: './venues-component.scss',
})
export class VenuesComponent {
  private venueService = inject(VenueService);
  private router = inject(Router);
  private chatService = inject(ChatService);
  private generateService = inject(GenerateService);

  venues = signal<VenueUi[]>([]);

  ngOnInit() {
    this.chatService.start().catch((err) => console.error('SignalR connection error:', err));
    this.loadVenues();
  }

  async loadVenues() {
    const rawVenues = await this.venueService.getVenues();

    const uiVenues = rawVenues.map((v) => ({
      ...v,
      loading: signal(false) as WritableSignal<boolean>,
      editing: signal(false) as WritableSignal<boolean>,
      generatedDescription: signal<string | null>(null) as WritableSignal<string | null>,
    }));

    this.venues.set(uiVenues);
  }

  protected goToVenue(venue: Venue) {
    this.router.navigate(['/venues', venue.slug]);
  }

  getBackgroundImage(url: string) {
    return url ? `url(${url})` : 'none';
  }

  async autoGenerateDescription(venue: VenueUi) {
    venue.loading.set(true);

    try {
      const res = await this.generateService.generateDescription(
        `Generate description for venue with name: ${venue.name} and location: ${venue.location}`
      );

      venue.generatedDescription.set(res.response ?? '');
      venue.editing.set(true);
    } catch (err) {
      console.error(err);
    } finally {
      venue.loading.set(false);
    }
  }
}
