import { ChatService } from './../../services/chat-service';
import { Component, computed, inject, signal, WritableSignal } from '@angular/core';
import { VenueService } from '../../services/venue-service';
import { Venue, VenueUi } from '../../models/Venue';
import { CardModule } from 'primeng/card';
import { ButtonModule } from 'primeng/button';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { GenerateService } from '../../services/generate-service';
import { SearchBar } from '../shared/search-bar/search-bar';

@Component({
  selector: 'app-venues-component',
  imports: [CardModule, ButtonModule, CommonModule, SearchBar],
  templateUrl: './venues-component.html',
  styleUrl: './venues-component.scss',
})
export class VenuesComponent {
  private venueService = inject(VenueService);
  private router = inject(Router);
  private chatService = inject(ChatService);
  private generateService = inject(GenerateService);

  venues = signal<VenueUi[]>([]);
  searchTerm = signal('');

  filteredVenues = computed(() => {
    const term = this.searchTerm().toLowerCase();
    if (!term) return this.venues();

    return this.venues().filter(
      (v) =>
        v.name.toLowerCase().includes(term) ||
        v.location.toLowerCase().includes(term) ||
        (v.description ?? '').toLowerCase().includes(term)
    );
  });

  ngOnInit() {
    this.chatService.start().catch((err) => console.error('SignalR connection error:', err));
    this.loadVenues();
  }

  async loadVenues() {
    const rawVenues = await this.venueService.getVenues();

    const uiVenues = rawVenues.map((v) => ({
      ...v,
      loading: signal(false) as WritableSignal<boolean>,
      editing: signal(false) as WritableSignal<boolean>,
      generatedDescription: signal<string | null>(null) as WritableSignal<string | null>,
    }));

    this.venues.set(uiVenues);
  }

  onSearch(term: string) {
    this.searchTerm.set(term);
  }

  protected goToVenue(venue: Venue) {
    this.router.navigate(['/venues', venue.slug]);
  }

  async autoGenerateDescription(venue: VenueUi) {
    venue.loading.set(true);

    try {
      const res = await this.generateService.generateDescription(
        `Generate description for venue with name: ${venue.name} and location: ${venue.location}`
      );

      venue.generatedDescription.set(res.response ?? '');
      venue.editing.set(true);
    } finally {
      venue.loading.set(false);
    }
  }

  async updateDescription(venue: VenueUi) {
    await this.venueService.updateVenueDescription(venue.id, venue.generatedDescription()!);
    venue.editing.set(false);
  }
}
